import { Organization } from "models/Organization";
import { Status } from "models/Status";
import { AppUser } from "models/AppUser/AppUser";
import { Store } from "./../Store/Store";
import { Moment } from "moment";
import { Model } from "@react3l/react3l/core";
import { RequestState } from "models/RequestState";
import { DirectSalesOrderContent } from "models/DirectSalesOrderContent";

export class DirectSalesOrder extends Model {
  public id?: number;
  public code?: string;
  public organizationId?: number;
  public buyerStoreId?: number;
  public phoneNumber?: string;
  public storeAddress?: string;
  public deliveryAddress?: string;
  public saleEmployeeId?: number;
  public orderDate?: Moment;
  public deliveryDate?: Moment;
  public erpApprovalStateId?: number;
  public positionId?: number;
  public provinceId: number;
  public storeApprovalStateId?: number;
  public requestStateId?: number;
  public editedPriceStatusId?: number;
  public note?: string;
  public subTotal?: number;
  public generalDiscountPercentage?: number;
  public generalDiscountAmount?: number;
  public totalTaxAmount?: number;
  public totalAfterTax?: number;
  public promotionCode?: string;
  public promotionValue?: number;
  public total?: number;
  public storeCheckingId?: number;
  public creatorId?: number;
  public storeUserCreatorId?: number;
  public directSalesOrderSourceTypeId?: number;
  public generalApprovalStateId?: number;
  public buyerStore?: Store;
  public creator?: AppUser;
  public editedPriceStatus?: Status;
  public erpApprovalState?: RequestState;
  public organization?: Organization;
  public directSalesOrderContents?: DirectSalesOrderContent[] = [];
  public requestState?: RequestState;
  public saleEmployee?: AppUser;
  public storeApprovalState?: RequestState;
  public generalApprovalState?: RequestState;
}
